export const IS_FETCHING = 'IS_FETCHING'

export const SET_COUNTRY_INFO = 'SET_COUNTRY_INFO'

export const SET_CURRENT_FINDER_AMOUNT = 'SET_CURRENT_FINDER_AMOUNT'

export const SET_FINDER_TEXT = 'SET_FINDER_TEXT'

export const SET_ERROR_QUERY = 'SET_ERROR_QUERY'
